---
abstract: 'Nested Commands Tree in Shell Interface'
author:
  - 'Josef Ezra <jezra@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Shell-MultiCmd
no_index:
  directory:
    - t
    - inc
requires:
  Term::ReadLine: 0
  Test::More: 0
  Text::ParseWords: 0
version: 1.093
